angular.module('app')
.config(function($stateProvider, $urlRouterProvider){
    $stateProvider.state('news',{
        url:'/news',
        templateUrl:'templates/news.html'
    })
        .state('news.companynews',{
        url:'/companynews',
            templateUrl:'templates/news/companynews.html'
    })
        .state('news.zixun',{
        url:'/zixun',
        templateUrl:'templates/news/zixun.html'
    })
        .state('product',{
            //产品分类
            url:'/product',
            templateUrl:'templates/product.html'
        })
        .state('product.product1',{
            url:'/product1',
            templateUrl:'templates/product/product1.html'
        })
        .state('product.product2',{
            url:'/product2',
            templateUrl:'templates/product/product2.html'
    })
        .state('product.product3',{
            url:'/product3',
            templateUrl:'templates/product/product3.html'
        })

    //成功案例
        .state('successcase',{
            url:'/successcase',
            templateUrl:'templates/successcase.html'
        })
        .state('successcase.case1',{
            url:'/case1',
            templateUrl:'templates/successcase/case1.html'
        })
        .state('successcase.case2',{
            url:'/case2',
            templateUrl:'templates/successcase/case2.html'
        })
        .state('successcase.case3',{
            url:'/case3',
            templateUrl:'templates/successcase/case3.html'
        })

        .state('service',{
            url:'/service',
            templateUrl:'templates/service.html'
        })
        .state('service.website',{
            url:'/website',
            templateUrl:'templates/service/website.html'
        })
        .state('service.weixin',{
           url:'/weixin',
            templateUrl:'templates/service/weixin.html'
        })
        .state('service.tuiguang',{
            url:'/tuiguang',
            templateUrl:'templates/service/tuiguang.html'
        })
        //在线留言
        .state('onlinemessage',{
            url:'/onlinemessage',
            templateUrl:'templates/onlinemessage.html'
        })
    //联系我们
        .state('contactus',{
            url:'/contactus',
            templateUrl:'templates/contactus.html'
        })
    ;


})